# kubectl apply -f luis-rivas-33-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: luis-rivas-33-secret
  namespace: luis-rivas-33-namespace
type: Opaque
data:
  PORTL: cjJkODA4NQ==
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9sdWlzcml2YXM6QWxleGFuZGVyMTkwM0BjbHVzdGVyMC5ncjRhdnVrLm1vbmdvZGIubmV0L2lhX2RiP2FwcE5hbWU9Q2x1c3RlcjA=   # en Base64
  DATABASE_USERNAME: aWFfZGI=   # en Base64
  DATABASE_PASSWORD: QWxleGFuZGVyMTkwMw==   # en Base64
  RAPIDAPI_URL: aHR0cHM6Ly9kZWVwLXRyYW5zbGF0ZTEucC5yYXBpZGFwaS5jb20=   # en Base64
  RAPIDAPI_HOST: ZGVlcC10cmFuc2xhdGUxLnAucmFwaWRhcGkuY29t   # en Base64
  RAPIDAPI_APIKEY: Yzc2NzBkYjIyOG1zaDRjMGFlZTVlOWEyY2UyMnAxNGJmOTVqc25kZmQwNjUxODJlNDM=   # en Base64

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode