# kubectl apply -f luis-rivas-33-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: luis-rivas-33-deployment
  namespace: luis-rivas-33-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: luis-rivas-33-deployment        # Debe coincidir con las etiquetas del Service
  template:
    metadata:
      labels:
        app: luis-rivas-33-deployment      # Debe coincidir con las etiquetas del Service
    spec:
      containers:
      - name: luis-rivas-33-container
        image: luisrivas3/as241-proyecto:latest   # Reemplaza con tu imagen Docker Hub
        imagePullPolicy: IfNotPresent        # Evitar traer siempre la última versión si hay una actual
        ports:
        - containerPort: 8080    # El puerto que tu app va a abrir
        env:
        - name: PORT            
          value: "8080"          
        envFrom:
        - secretRef:
            name: luis-rivas-33-secret  # Esto cargará todos los valores como variables de entorno